# Generated by Django 5.1.2 on 2024-10-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_palabraclave'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopdf',
            name='texto',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='PalabraClave',
        ),
    ]
